//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PaintTool
{
    public partial class PaintTool
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.FileUpload FileUpload1;

        protected global::System.Web.UI.WebControls.Button BtnUpload;

        protected global::System.Web.UI.WebControls.Image UploadedImage;

        protected global::System.Web.UI.WebControls.HiddenField UploadedImagePath;
    }
}
